### ISSUE TITLE
请问下大佬这个插件应该怎么用？

### ISSUE THREAD

**Issue by FruitMilk123** [DarrenIce/NGA-MoFish#1]
下好了之后选择一个命令都会报： command 'nga-xxx' not found

**Comment by DarrenIce** [comment]
已经修复了，稍等更新到1.1.2就可以了，抱歉发布之前没有测= =
使用的话先Login填cookie，然后自己添加分区对应的fid就可以了

**Comment by FruitMilk123** [comment]
刚刚更新到了1.1.2了。请问下cookie是从哪里获取的？ 另外在登陆的情况下直接添加分区（填了一个-7）然后报了403错误是正常的吗------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;DarrenIce&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月26日(星期二) 中午1:59
收件人:&nbsp;&quot;DarrenIce/NGA-MoFish&quot;<NGA-MoFish@noreply.github.com&gt;;
抄送:&nbsp;&quot;吴永伟&quot;<1042478501@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DarrenIce/NGA-MoFish] 请问下大佬这个插件应该怎么用？ (#1)

**Comment by DarrenIce** [comment]
> 刚刚更新到了1.1.2了。请问下cookie是从哪里获取的？ 另外在登陆的情况下直接添加分区（填了一个-7）然后报了403错误是正常的吗------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;DarrenIce&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月26日(星期二) 中午1:59 收件人:&nbsp;&quot;DarrenIce/NGA-MoFish&quot;<NGA-MoFish@noreply.github.com&gt;; 抄送:&nbsp;&quot;吴永伟&quot;<1042478501@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [DarrenIce/NGA-MoFish] 请问下大佬这个插件应该怎么用？ (#1)

F12，然后刷新论坛，在network里面找url请求，请求头里面有cookie，全部复制进去就可以了。403错误就是没有登录的意思

**Comment by FruitMilk123** [comment]
找了半个小时终于找到cookie了，登上去了…感谢大佬------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;DarrenIce&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月26日(星期二) 下午2:21
收件人:&nbsp;&quot;DarrenIce/NGA-MoFish&quot;<NGA-MoFish@noreply.github.com&gt;;
抄送:&nbsp;&quot;吴永伟&quot;<1042478501@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DarrenIce/NGA-MoFish] 请问下大佬这个插件应该怎么用？ (#1)
