### ISSUE TITLE
只看楼主这里点击之后没办法切换回来

### ISSUE THREAD

**Issue by lanxisama** [DarrenIce/NGA-MoFish#11]
只可以点击只看楼主，但是想重新看全部帖子没办法

**Comment by DarrenIce** [comment]
增加了取消只看楼主的按钮，不过不是很美观，中秋回来再优化吧hhh

**Comment by lanxisama** [comment]
建议只看楼主按钮点击之后把原按钮修改一下

**Comment by DarrenIce** [comment]
一开始是这么想的，不过当时脑子有点抽风，有个bug没想明白，等周三上班了我回去改一下应该就可以了。

**Comment by DarrenIce** [comment]
已更新，等1.3.9版本看一下~

**Comment by lanxisama** [comment]
> 已更新，等1.3.9版本看一下~

好的 一会看一下
