### ISSUE TITLE
希望能出一个分页的功能

### ISSUE THREAD

**Issue by SmileINF** [DarrenIce/NGA-MoFish#14]
浏览比较长的帖子时，加载时间有点长

**Comment by DarrenIce** [comment]
已更新在1.4.4中，等上线后可以看一下

**Comment by SmileINF** [comment]
哇，大佬牛皮




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DarrenIce/NGA-MoFish"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月23日(星期四) 下午4:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DarrenIce/NGA-MoFish] 希望能出一个分页的功能 (#14)





 
已更新在1.4.4中，等上线后可以看一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
