### ISSUE TITLE
不知道url和要复制的部分是怎么样的，readme那里没图，不知道怎么登录，我zsbd

### ISSUE THREAD

**Issue by sweetlj** [DarrenIce/NGA-MoFish#15]
可以看到有类似于这样的url，在请求标头中找到cookie，复制

**Comment by DarrenIce** [comment]
打开浏览器，然后F12打开开发者工具，切到Network一栏
打开NGA论坛，登录，在Network里找到nga的url，把里面的cookie复制进来就可以了

**Comment by sweetlj** [comment]
> 
谢谢，登上了
我先登出，然后清掉network，选到All，登入，输账号密码之后，再输验证码，确定之后页面会提示我是否要刷新页面，刷新页面之后出了名字是bbs.nga.cn的请求，复制request headers里的Cookie，不懂怎么登入的xdm可以跟着我这个步骤来做
