### ISSUE TITLE
高强度刷帖报错了

### ISSUE THREAD

**Issue by sweetlj** [DarrenIce/NGA-MoFish#16]
Maximum number of redirects exceeded

**Comment by DarrenIce** [comment]
可以具体说明是怎么触发的吗，是点击了哪个帖子产生的。开发人员工具的控制台有无错误输出？

**Comment by sweetlj** [comment]
> 可以具体说明是怎么触发的吗，是点击了哪个帖子产生的。开发人员工具的控制台有无错误输出？

在刷二手交易这个节点时，快速点击各个帖子，想用过滤已读帖子的功能来找自己想要的二手东西，然后就报了这个错
Maximum number of redirects exceeded

现在倒没报这个错了，报的是
Request failed with status code 403

网页的开发者控制台报错
about:blank:1 GET about:blank net::ERR_UNKNOWN_URL_SCHEME
但网页没问题，可以正常刷帖

**Comment by DarrenIce** [comment]
应该是频繁请求nga的接口导致的吧，一般等几秒刷新就可以了
