### ISSUE TITLE
登录成功了，但是需要权限的帖子还是不能看

### ISSUE THREAD

**Issue by wangshantao** [DarrenIce/NGA-MoFish#21]
比如这个帖子 https://bbs.nga.cn/read.php?tid=35508113

![微信截图_20230302154053](https://user-images.githubusercontent.com/14883268/222363574-e54113c8-0257-48b7-85c6-5784d1587021.png)

**Comment by DarrenIce** [comment]
有一些刚发布或者刚回复的贴子是有问题的，因为从接口获取到的json不完整，或者用户名中有特殊的字符导致json无法解析，没什么好的办法
