### ISSUE TITLE
无法通过postMessage向webview中传递事件

### ISSUE THREAD

**Issue by ys152452** [DarrenIce/NGA-MoFish#24]
打算做点赞功能，需要在webview中对点赞数进行局部刷新，使用loadTopicInPanel会存在闪烁和重置滚动条的体验问题
简单测试代码如下：
topicWebview.ts中触发
`
panel.webview.postMessage({command: 'update'});
`
topic-spic或topic中接收
`
window.addEventListener('message', event => {
  console.log(event);
});
`

**Comment by ys152452** [comment]
怀疑是否与art-template有关

**Comment by DarrenIce** [comment]
前端我也是半吊子水平，等出差回去我看一下hhh

**Comment by DarrenIce** [comment]
我在最新的1.5.3中支持了点赞功能，测试了一下没有闪烁的问题，你可以看一下。
