### ISSUE TITLE
某个版面的子页面虽然可以显示在节点列表中, 但是无法读取

### ISSUE THREAD

**Issue by shutongX** [DarrenIce/NGA-MoFish#25]
看了逻辑代码, 目前所有读节点都是读的fid
但是版面的子页面的id是stid
eg: https://nga.178.com/thread.php?stid=34478370
这样的面板能够显示在节点列表里, 但是无法读取topic

**Comment by DarrenIce** [comment]
这种讨论合集确实没有适配进去，这几天有空我会加一下

**Comment by shutongX** [comment]
> 这种讨论合集确实没有适配进去，这几天有空我会加一下

本来想自己搞这个功能, 结果发现fid耦合的地方有点多, 没敢动

**Comment by DarrenIce** [comment]
更新了1.6.2版本，可以试用一下，新版在添加节点时输入stid=xxx就可以了

**Comment by shutongX** [comment]
更新完直接什么命令都执行不了了, 发生甚么事了

**Comment by shutongX** [comment]
![Snipaste_2023-09-21_09-04-56](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/f00f788d-110f-4b14-b3a1-9fdc7eefb364)
如图所示, 更新到1.6.2或者1.7.0都会发生这样的问题, 所以只能回退到1.6.1

**Comment by DarrenIce** [comment]
#4 可以参考一下这个issue，看一下开发人员工具中有什么报错

**Comment by DarrenIce** [comment]
我本地没办法复现这个bug = =

**Comment by shutongX** [comment]
![image](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/d8f69d0c-b152-43a4-88ec-fd8e801a3624)
看起来是name字段不存在?

**Comment by shutongX** [comment]
![image](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/b8e696f6-9cbe-408b-88cd-d0ce8e02c6a9)
![image](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/339d677c-faae-475a-9aef-7768d815b9a0)
对比了一下新老两个版本, 感觉是把title错误的使用了name, name是个数字
![image](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/f03688b7-bec0-402d-b3cb-57d8408ebb0d)

**Comment by DarrenIce** [comment]
了解了。
因为这次改了node.name的形式，我也不想让之前的人再手动修改一次，就做了一个这样的替换，看来需要再改一下

**Comment by DarrenIce** [comment]
更新了1.7.1，稍后可以试一下

**Comment by shutongX** [comment]
牛的, 已经成功导入了, 而且感觉好像加载速度比以前快了

**Comment by shutongX** [comment]
![image](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/7fca2a9b-234b-4ec0-bb70-327f45908065)
不对, 在打开具体页面的时候又报错了, 看起来是json体处理的问题

**Comment by shutongX** [comment]
![image](https://github.com/DarrenIce/NGA-MoFish/assets/24763269/3ab7332c-0142-4c73-b7de-0288caaf6f4e)

**Comment by DarrenIce** [comment]
应该是个别帖子会这样吧，这是nga的问题。有的帖子请求到的json不完整，也可能是有的人id有特殊符号，json无法解析

**Comment by shutongX** [comment]
重启vscode之后好了
