### ISSUE TITLE
老哥可以加个178的域名吗

### ISSUE THREAD

**Issue by joshuapex** [DarrenIce/NGA-MoFish#26]
nga被公司屏蔽了,但是178没有,想来个曲线摸鱼

**Comment by GavinAndre** [comment]
公司nga和178都屏蔽了 能否像v2ex-playground一样提供个设置代理的地方

**Comment by DarrenIce** [comment]
@joshuapex 增加了自定义域名的功能，更新1.7.0后在设置-域名设置中修改域名为nga.178.com即可
@GavinAndre 增加了设置代理的功能，更新1.7.0后在设置-代理设置中添加代理即可
