### ISSUE TITLE
建议topic列表去掉版面标题

### ISSUE THREAD

**Issue by Jay-Young** [DarrenIce/NGA-MoFish#3]
名字短一点的版面标题还好，长了连标题都看不到了，把窗口拉宽一点可以解决，但还是希望去掉版面标题，用处好像不大。
![image](https://user-images.githubusercontent.com/8641055/108817802-6c55d800-75f3-11eb-8042-b1ace319fc60.png)
另外子版面的显示设定看NGA的接口应该是跟着网页版的设置的，不知道是否有其他办法设置保持两者不同步，NGA好像是没有提供相关设置接口。

**Comment by DarrenIce** [comment]
1, 版面标题这个，因为经常逛水区，所以想看到子版标题，我后续改一下位置吧，放到详情页里面
2. 子版面这个，你是想让它屏蔽掉吗？

**Comment by Jay-Young** [comment]
@DarrenIce 
是的。目前子版面是根据cookie来读取网页版设置的，网页版我想看全部子版面，但是在vscode里摸鱼的时候我可能不想看或者不方便看某些子版面，希望能够屏蔽。
另外你的svg图标有问题，无法显示。
![image](https://user-images.githubusercontent.com/8641055/108819561-f69f3b80-75f5-11eb-8de6-a881f3d87d47.png)
我从[iconfront](https://www.iconfont.cn/search/index?searchType=icon&q=nga&page=1&fromCollection=-1&fills=&tag=)找了一个替换了可以正常显示了。
![image](https://user-images.githubusercontent.com/8641055/108819676-1b93ae80-75f6-11eb-9983-b4995fb0382e.png)

**Comment by DarrenIce** [comment]
屏蔽这个等我想一下怎么实现比较合理
图标已经替换了
子标题目前修改成最多显示前5个了，这样不会太长，也能够大概看到是哪个子板

**Comment by DarrenIce** [comment]
更新了1.2.5，这个版本严格限制了版面内容，比如如果fid是网事杂谈，那么只会出现网事杂谈title的帖子，大时代这些子版的帖子就不会出现了。如果想看某几个子版，可以添加子版对应的fid。
