### ISSUE TITLE
[Bug] 任何板块都打不开

### ISSUE THREAD

**Issue by hufengxiao** [DarrenIce/NGA-MoFish#30]
![Screenshot 2024-05-24 10-59-56](https://github.com/DarrenIce/NGA-MoFish/assets/37281576/80f3a92b-1322-46f0-979f-b8b0497a1bd6)

1. 打开板块时 
getaddrinfo EAI_AGAIN bbs.nga.cn

2. 添加板块时 
Error running command nga-custom.addNode: A system error occurred (getaddrinfo EAI_AGAIN bbs.nga.cn). This is likely caused by the extension that contributes nga-custom.addNode.

**Comment by DarrenIce** [comment]
抱歉现在才看到，我这边没有复现这个问题。可能需要你这边检查下自己的网络，或者在设置里面把nga域名改成nga.178.com重新尝试一下。

**Comment by hufengxiao** [comment]
> 抱歉现在才看到，我这边没有复现这个问题。可能需要你这边检查下自己的网络，或者在设置里面把nga域名改成nga.178.com重新尝试一下。

就那天用的时候出现了这个问题，然后再次使用的时候没出现了。可能是我的网络问题吧
