### ISSUE TITLE
打不开帖子，加载Web视图时出错

### ISSUE THREAD

**Issue by Tamanegii** [DarrenIce/NGA-MoFish#31]
点击帖子之后提示：
加载 Web 视图时出错: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
无法显示任何内容

**Comment by Tamanegii** [comment]
不知道发生了什么，但是昨天晚上系统崩溃重启之后就又能打开了...

**Comment by joshuapex** [comment]
从这个星期一开始我也遇到这个问题了，重启以后也打不开
