### ISSUE TITLE
插件安装之后无法正常使用

### ISSUE THREAD

**Issue by chencodeX** [DarrenIce/NGA-MoFish#4]
安装之后点击登录NGA，提示
command 'nga.login' not found
其他几个按钮类似

尝试过reload和重启vsc，没有作用
macos

**Comment by DarrenIce** [comment]
没有mac环境，在win上面没办法复现这个bug...很抱歉

**Comment by chencodeX** [comment]
我看您之前在 别的 issue里提过修复了类似问题，v1.1.2
这次修复的问题，主要是什么原因呢？
有没有什么行之有效的debug方式可以参考？

**Comment by DarrenIce** [comment]
当时好像是配置文件里写错了(毕竟写的第一个vscode插件，好多都是摸索的，瞎改了改就能用了= =。

**Comment by chencodeX** [comment]
撞大运编程

**Comment by DarrenIce** [comment]
是这样的，毕竟也不是写前端的，凑合能用就行hhhhhh

**Comment by ShirleyMatrix** [comment]
Maybe Fixed in #6

**Comment by LynahZ** [comment]
> Maybe Fixed in #6 

好像mac还是不太行
command 'nga.login' not found

macOS 11.5
VS Code 1.58.2

**Comment by lanxisama** [comment]
mac环境还是nga.login not found 太难了 sad

**Comment by ShirleyMatrix** [comment]
@LynahZ @lanxisama 
_我也不知道，就莫名其妙的行了（_

如果还是不行的话，试试直接下载用visx安装
_我当时是自己打包了一份，装上就没问题，但是商店的就会报错_

还有就是可以在vscode里，点击 帮助-切换开发人员工具
然后切换到console ，找到里面对应摸鱼插件的报错信息，然后提供出来，有利于修复bug

**Comment by LynahZ** [comment]
@ShirleyMatrix 

<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">workbench.desktop.main.js:sourcemap:2038</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;">Activating extension 'DarrenB.nga-mofish' failed: dlopen(/Users/xxx/.vscode/extensions/darrenb.nga-mofish-1.3.4/node_modules/iconv/build/Release/iconv.node, 1): no suitable image found.  Did find:
        /Users/xxx/.vscode/extensions/darrenb.nga-mofish-1.3.4/node_modules/iconv/build/Release/iconv.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00
	/Users/xxx/.vscode/extensions/darrenb.nga-mofish-1.3.4/node_modules/iconv/build/Release/iconv.node: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00.</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: menlo, monospace; --source-code-font-size: 11px; --source-code-font-family: menlo, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | $onExtensionActivationError | @ | workbench.desktop.main.js:sourcemap:2038
-- | -- | -- | --
  | _doInvokeHandler | @ | workbench.desktop.main.js:sourcemap:1551
  | _invokeHandler | @ | workbench.desktop.main.js:sourcemap:1551
  | _receiveRequest | @ | workbench.desktop.main.js:sourcemap:1551
  | _receiveOneMessage | @ | workbench.desktop.main.js:sourcemap:1551
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:1551
  | fire | @ | workbench.desktop.main.js:sourcemap:60
  | fire | @ | workbench.desktop.main.js:sourcemap:76
  | _receiveMessage | @ | workbench.desktop.main.js:sourcemap:76
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:76
  | fire | @ | workbench.desktop.main.js:sourcemap:60
  | acceptChunk | @ | workbench.desktop.main.js:sourcemap:76
  | (anonymous) | @ | workbench.desktop.main.js:sourcemap:76
  | T | @ | workbench.desktop.main.js:sourcemap:2899
  | emit | @ | events.js:315
  | addChunk | @ | internal/streams/readable.js:309
  | readableAddChunk | @ | internal/streams/readable.js:284
  | Readable.push | @ | internal/streams/readable.js:223
  | onStreamRead | @ | internal/stream_base_commons.js:188

</span></div>


<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">workbench.desktop.main.js:749</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: command 'nga.login' not found
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at g._tryExecuteCommand (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1525</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1525</span>
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at processTicksAndRejections (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">internal/process/task_queues.js:93</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async D.runAction (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:174</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async D.run (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:174</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at async u.onClick (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:664</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(189, 198, 207); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: menlo, monospace; --source-code-font-size: 11px; --source-code-font-family: menlo, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | onDidChangeNotification | @ | workbench.desktop.main.js:749
-- | -- | -- | --
  | (anonymous) | @ | workbench.desktop.main.js:749
  | fire | @ | workbench.desktop.main.js:60
  | addNotification | @ | workbench.desktop.main.js:751
  | error | @ | workbench.desktop.main.js:1589
  | (anonymous) | @ | workbench.desktop.main.js:1989
  | fire | @ | workbench.desktop.main.js:60
  | run | @ | workbench.desktop.main.js:174
  | processTicksAndRejections | @ | internal/process/task_queues.js:93
  | async function (async) |   |  
  | run | @ | workbench.desktop.main.js:174
  | onClick | @ | workbench.desktop.main.js:664
  | (anonymous) | @ | workbench.desktop.main.js:174
  | processImmediate | @ | internal/timers.js:461

</span></div>

**Comment by ShirleyMatrix** [comment]
@DarrenIce 
https://github.com/DarrenIce/NGA-MoFish/blob/96cbcdab7de5ff77341afef5ab94bae52d1955c6/src/global.ts#L3
从报错看相关的语句只有这个, 而且是无用的语句, 能否尝试移除发布一个新的版本呢

**Comment by DarrenIce** [comment]
@ShirleyMatrix 已更新，稍后可以再试一下

**Comment by ShirleyMatrix** [comment]
@chencodeX @LynahZ @lanxisama  更新了1.3.5 可以测试一下bug有没有修复

**Comment by LynahZ** [comment]
> @chencodeX @LynahZ @lanxisama 更新了1.3.5 可以测试一下bug有没有修复

可以，牛啊！

**Comment by chencodeX** [comment]
然鹅我已经失去了我的mac
