### ISSUE TITLE
建议加个是否显示AC娘表情选项

### ISSUE THREAD

**Issue by 404-code** [DarrenIce/NGA-MoFish#5]
满足不同的摸鱼人群

**Comment by DarrenIce** [comment]
可以，等我摸鱼写一下~

**Comment by DarrenIce** [comment]
加好了，一会更新推送了可以看一下~不过只能关掉部分，有的nga表情是img形式展示出来的，这部分没办法关，要关就会屏蔽全部图片

**Comment by 404-code** [comment]
> 加好了，一会更新推送了可以看一下~不过只能关掉部分，有的nga表情是img形式展示出来的，这部分没办法关，要关就会屏蔽全部图片

ok,哪天能摸鱼了试试看

**Comment by Gaays** [comment]
确实有些表情无法关闭，能否做成那种点击后才显示图片的呢？有的帖子图片太多了

**Comment by DarrenIce** [comment]
> 确实有些表情无法关闭，能否做成那种点击后才显示图片的呢？有的帖子图片太多了

ok，等有空研究一下这个

**Comment by DarrenIce** [comment]
> 确实有些表情无法关闭，能否做成那种点击后才显示图片的呢？有的帖子图片太多了

曲线救国了一下，开关AC娘变成了全局小图模式，点小图可以看大图，小图感觉还挺小的，应该可以摸鱼吧

**Comment by DarrenIce** [comment]
现在有无图模式了，通杀了hhhhh

**Comment by Gaays** [comment]
可以的，测了一下发现表情和图片都能不显示，完美满足
上次在办公室看到一个帖子打开是穿情趣内衣的美女大图，直接给我干蒙了
