### ISSUE TITLE
列表栏帖子重复重复

### ISSUE THREAD

**Issue by lanxisama** [DarrenIce/NGA-MoFish#9]
<img width="459" alt="656B0764-1A82-487C-B1BC-8CE26ED81451" src="https://user-images.githubusercontent.com/31368658/133784383-f71b8dea-5451-4e3e-bcfc-3cedacd81d87.png">

截图在这，有时间看一下吧

**Comment by lanxisama** [comment]
done 已经合进去了

**Comment by DarrenIce** [comment]
刚写出来的时候就发现这个Bug了，不过一直没时间修hhh，多谢commit
